### ISSUE TITLE
Copyright please

### ISSUE THREAD

**Issue by EggPool** [DanielChain/PyChain#1]
GPL license does not prevent from citing the source of the work.

This project is a clone of Bismuth, due credit in the licence and main readme would be appreciated.
https://github.com/hclivess/Bismuth

Thanks!

**Comment by DanielChain** [comment]
Done.

EggPool <notifications@github.com> schrieb am Mi., 3. Okt. 2018, 12:57
nachm.:

**Comment by EggPool** [comment]
Thanks!
